//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn6.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<int> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getdata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getdata();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getdata", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getdataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInformationDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getInformationDepartment(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInformationDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getInformationDepartmentAsync(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInformationEmplayee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getInformationEmplayee(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInformationEmplayee", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getInformationEmplayeeAsync(string ten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaphongban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getMaphongban(string tenPB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaphongban", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getMaphongbanAsync(string tenPB);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaChucVu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getMaChucVu(string tenCV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaChucVu", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getMaChucVuAsync(string tenCV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool insert(string manv, string tennv, string gioitinh, string trinhdo, System.DateTime ngaysinh, string honnhn, string socmnn, string que, string phone, string email, string phongban, string cv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insert", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> insertAsync(string manv, string tennv, string gioitinh, string trinhdo, System.DateTime ngaysinh, string honnhn, string socmnn, string que, string phone, string email, string phongban, string cv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTinhTrang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getTinhTrang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTinhTrang", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getTinhTrangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaNV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMaNV(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaNV", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMaNVAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ImportEmployees(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ImportEmployeesAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTest", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInformationNhanVien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetInformationNhanVien(string maNV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInformationNhanVien", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetInformationNhanVienAsync(string maNV);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : DoAn6.ServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<DoAn6.ServiceReference2.WebService1Soap>, DoAn6.ServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<int> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet getdata() {
            return base.Channel.getdata();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getdataAsync() {
            return base.Channel.getdataAsync();
        }
        
        public System.Data.DataSet getAccount() {
            return base.Channel.getAccount();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAccountAsync() {
            return base.Channel.getAccountAsync();
        }
        
        public System.Data.DataSet getInformationDepartment(string ten) {
            return base.Channel.getInformationDepartment(ten);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getInformationDepartmentAsync(string ten) {
            return base.Channel.getInformationDepartmentAsync(ten);
        }
        
        public System.Data.DataSet getInformationEmplayee(string ten) {
            return base.Channel.getInformationEmplayee(ten);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getInformationEmplayeeAsync(string ten) {
            return base.Channel.getInformationEmplayeeAsync(ten);
        }
        
        public string getMaphongban(string tenPB) {
            return base.Channel.getMaphongban(tenPB);
        }
        
        public System.Threading.Tasks.Task<string> getMaphongbanAsync(string tenPB) {
            return base.Channel.getMaphongbanAsync(tenPB);
        }
        
        public string getMaChucVu(string tenCV) {
            return base.Channel.getMaChucVu(tenCV);
        }
        
        public System.Threading.Tasks.Task<string> getMaChucVuAsync(string tenCV) {
            return base.Channel.getMaChucVuAsync(tenCV);
        }
        
        public bool insert(string manv, string tennv, string gioitinh, string trinhdo, System.DateTime ngaysinh, string honnhn, string socmnn, string que, string phone, string email, string phongban, string cv) {
            return base.Channel.insert(manv, tennv, gioitinh, trinhdo, ngaysinh, honnhn, socmnn, que, phone, email, phongban, cv);
        }
        
        public System.Threading.Tasks.Task<bool> insertAsync(string manv, string tennv, string gioitinh, string trinhdo, System.DateTime ngaysinh, string honnhn, string socmnn, string que, string phone, string email, string phongban, string cv) {
            return base.Channel.insertAsync(manv, tennv, gioitinh, trinhdo, ngaysinh, honnhn, socmnn, que, phone, email, phongban, cv);
        }
        
        public System.Data.DataTable getTinhTrang() {
            return base.Channel.getTinhTrang();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getTinhTrangAsync() {
            return base.Channel.getTinhTrangAsync();
        }
        
        public int Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public string GetMaNV(string userName, string password) {
            return base.Channel.GetMaNV(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> GetMaNVAsync(string userName, string password) {
            return base.Channel.GetMaNVAsync(userName, password);
        }
        
        public bool ImportEmployees(string sql) {
            return base.Channel.ImportEmployees(sql);
        }
        
        public System.Threading.Tasks.Task<bool> ImportEmployeesAsync(string sql) {
            return base.Channel.ImportEmployeesAsync(sql);
        }
        
        public bool DeleteTest() {
            return base.Channel.DeleteTest();
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTestAsync() {
            return base.Channel.DeleteTestAsync();
        }
        
        public System.Data.DataSet GetInformationNhanVien(string maNV) {
            return base.Channel.GetInformationNhanVien(maNV);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetInformationNhanVienAsync(string maNV) {
            return base.Channel.GetInformationNhanVienAsync(maNV);
        }
    }
}
